title: Cancelled by Netflix
description: >
  The shows Netflix decided to cancel - even those beloved by many. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Cancelled by Netflix# add your name
image: x-circle.svg # add your photo
about: Remembering the <span style="color:red;"><b>*count*</b></span> shows that Netflix let go, but fans won't forget (most of) them
social-github: jtmullen/cancelledbynetflix # add your Github handle

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jemoji


collections:
  - shows

exclude: ["_deploy_config.yml", "**/README.md"]
