title: Cancelled by Netflix
description: >
  Tracking Every Show Cancelled by Netflix Show Far. Some good, some bad, many fans wanted more of. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cancelledbynetflix.net" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Cancelled by Netflix # add your name
image: x-circle.svg # add your photo
about: Remembering the <span style="color:red;"><b>*count*</b></span> shows that Netflix let go, but fans won't forget (most of) them
social-github: jtmullen/cancelledbynetflix # add your Github handle

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jemoji


collections:
  - shows

exclude: ["_config.yml", "**/README.md"]
