name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "10 10 * * *"

jobs:
  linkCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH Pages Branch
        uses: actions/checkout@v3
        with: 
          ref: gh-pages
          
      - name: Check Links
        id: link-check
        uses: lycheeverse/lychee-action@v1.5.4
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --no-progress  --retry-wait-time 2 -a 403 --max-retries 10 './**/*.md' './**/*.html'

      - name: Create Issue If Broken Link
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with: 
          title: "Broken Link Report"
          content-filepath: ./lychee/out.md